# Generated by Django 5.0.4 on 2024-04-18 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_model", models.CharField(max_length=20)),
                ("car_company", models.CharField(max_length=20)),
                (
                    "year",
                    models.DateField(help_text="the year in which the car was made"),
                ),
                (
                    "made_in",
                    models.CharField(help_text="made in which country", max_length=10),
                ),
                ("milage", models.FloatField()),
                (
                    "tansmisstion_type",
                    models.CharField(
                        choices=[
                            ("auto", "auto transmission"),
                            ("manual", "manual transmission"),
                            ("cvt", "continuous variable transmission CVT "),
                        ],
                        max_length=6,
                    ),
                ),
                (
                    "drivetrain",
                    models.CharField(
                        choices=[
                            ("awd", "all wheel drive"),
                            ("fwd", "front-wheel drive"),
                            ("rwd", "rear-wheel drive"),
                            ("4wd", "four-wheel drive"),
                        ],
                        max_length=3,
                    ),
                ),
                ("auction_start_time", models.DateTimeField(auto_now_add=True)),
                ("auction_end_date", models.DateTimeField(auto_now=True)),
                ("available_for_auction", models.BooleanField()),
                ("images", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-auction_start_time"],
            },
        ),
    ]
