# Generated by Django 5.0.4 on 2024-04-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_tansmisstion_type_car_transmission_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="images",
            field=models.ImageField(blank=True, null=True, upload_to="cars/"),
        ),
    ]
