# Generated by Django 5.0.4 on 2024-04-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_car_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="appuser",
            name="about_me",
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="appuser",
            name="profile_img",
            field=models.ImageField(blank=True, null=True, upload_to="profile_imgs/"),
        ),
    ]
